name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cargo-clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev
      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1
        with:
          components: clippy
          cache-workspaces: src-tauri -> target

      - run: cargo install --path ./src-tauri
      - run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: ./src-tauri
