name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cargo-clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          components: clippy

      - run: cargo install --path ./src-tauri
      - run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: ./src-tauri
